# Generated by Django 4.1.13 on 2024-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=15)),
                ('mobileNumber', models.CharField(default='', max_length=12)),
                ('observation', models.CharField(default=None, max_length=255, null=True)),
                ('createdDate', models.DateField()),
                ('lastModifiedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
