# Generated by Django 4.1.13 on 2024-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='observation',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
