# Generated by Django 4.1.13 on 2024-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
