# Generated by Django 4.1.13 on 2024-01-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_paidamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.PositiveIntegerField(),
        ),
    ]
