# Generated by Django 4.1.13 on 2023-12-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('sellingPrice', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('createdDate', models.DateField(auto_now=True)),
                ('lastModifiedDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
