# Generated by Django 4.1.13 on 2023-12-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('count', models.IntegerField(default='')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('sellingPrice', models.DecimalField(decimal_places=2, default='', max_digits=5)),
            ],
        ),
    ]
