# Generated by Django 4.1.13 on 2023-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
    ]
