# Generated by Django 4.1.13 on 2023-12-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='lastModifiedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
