# Generated by Django 4.1.13 on 2023-12-10 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 13, 36, 3, 371243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='lastModifiedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
