# Generated by Django 4.1.13 on 2023-12-10 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_createddate_product_lastmodifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 13, 51, 42, 290381, tzinfo=datetime.timezone.utc)),
        ),
    ]
